# 簡易資料分析


## 沒有資料？就自己生囉！


In [ ]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [12]:
## 使用 numpy 的 random
import numpy as np

np.random.randint(1, 100) # 從 1 ~ 99 取出亂數。


6

## 神奇的 nparray

能不用迴圈就不要用迴圈吧！


In [28]:
import numpy as np

# 這是一個普通 list
p = [12, 24, 75, 33]
print(type(p))
print(p)

p = np.array(p)
print(type(p))
print(p)

# 神奇 array 直接幫你吧 array 內所有值都 * 3
print(p * 3)


<class 'list'>
[12, 24, 75, 33]
<class 'numpy.ndarray'>
[12 24 75 33]
[ 36  72 225  99]


In [33]:
scores = np.array([68, 80, 90])
權重 = np.array([0.2, 0.3, 0.5])
print('兩個 array 做內積 ＝ ', np.dot(scores, 權重))

# 相當於

print('兩個 array 相乘的和', (scores * 權重).sum())


## 二維資料比較接近現實。
# 假設有 5 個學生的成績
scores = np.array([[68, 80, 90], [50, 60, 65], [56, 86, 65], [62, 85, 77], [23, 34, 45]])
權重 = np.array([0.2, 0.3, 0.5])

# 原理就是 每一個 元素 都做 dot 運算。
print('5 個學生的學期成績 ＝', np.dot(scores, 權重))

兩個 array 做內積 ＝  82.6
兩個 array 相乘的和 82.6
5 個學生的學期成績 ＝ [ 82.6  60.5  69.5  76.4  37.3]


In [34]:
# numpy 套件的 random 功能可以取得 常態分佈的亂數。
# 也就是 平均值 0 標準差 1 的資料集。
np.random.randn(100)

array([ 0.0310803 ,  0.46206984,  0.80446874,  0.73743939,  1.08200201,
        0.07020305, -0.3613373 , -0.2924351 ,  1.04977821,  1.25332858,
        0.65335049, -0.63267289,  0.3632504 ,  1.87499774, -0.35846822,
        1.27505707,  1.99059637, -1.54628659, -1.95038951, -0.64072791,
       -1.22411324,  0.14609413, -0.68339367, -0.4721318 ,  0.10053239,
        0.37209613,  0.10378389, -0.42119982, -1.24132997,  0.26407215,
       -1.29498335, -2.63952777,  0.10461856, -0.12129959, -1.77098422,
        1.28275386,  1.55659085, -0.06119052, -0.55045242, -0.7472166 ,
       -1.4217234 , -0.50196255,  1.53217846,  0.72335998, -0.67726332,
       -1.00880075,  0.3285239 ,  1.69927312, -0.26365578,  1.73457675,
        0.18172234,  1.48300474, -0.78758539,  0.18107966, -0.85075326,
       -0.15045184, -0.32320938,  1.95222623,  0.12564649,  0.2569678 ,
        0.40345108, -1.01009748,  0.38910267,  0.05182356,  2.33577625,
        1.27799635, -1.78134965, -0.37144166, -0.0964149 , -0.73

In [70]:
# 調整範圍
scores = np.random.randn(100) * 10 + 70
scores

array([ 63.75503256,  77.73669292,  79.93498345,  52.45259407,
        68.70055008,  71.87704601,  81.3799592 ,  81.01259826,
        63.99911244,  63.67317294,  63.15571562,  62.08077453,
        58.37305913,  67.68526142,  78.0331307 ,  62.54093323,
        74.18923236,  72.90463089,  67.56790406,  54.13710591,
        76.49488897,  84.91868719,  65.64384406,  58.51831425,
        73.77344545,  84.5912662 ,  71.85414532,  76.33504082,
        68.80351382,  53.66706052,  70.13903576,  75.46674823,
        61.26621798,  67.89203982,  79.91829156,  68.45354036,
        97.58612187,  72.71155332,  50.31499429,  67.71861793,
        64.60460512,  71.82518257,  56.80053842,  65.79272175,
        74.64998395,  77.64191168,  58.83706614,  74.9597005 ,
        73.12667051,  67.26168115,  72.18392759,  77.54850316,
        75.10693855,  71.98817254,  67.32554527,  67.84111064,
        69.21657469,  69.14036002,  70.85093372,  74.37554729,
        81.66993671,  75.60664251,  66.14000305,  59.90

## 再來一個神奇的變身

直接把 1 * 100 的陣列變成 10 * 10 的二維陣列。


In [76]:
print(scores.shape)

scores.shape = (10, 10)
scores

(10, 10)


array([[ 63.75503256,  77.73669292,  79.93498345,  52.45259407,
         68.70055008,  71.87704601,  81.3799592 ,  81.01259826,
         63.99911244,  63.67317294],
       [ 63.15571562,  62.08077453,  58.37305913,  67.68526142,
         78.0331307 ,  62.54093323,  74.18923236,  72.90463089,
         67.56790406,  54.13710591],
       [ 76.49488897,  84.91868719,  65.64384406,  58.51831425,
         73.77344545,  84.5912662 ,  71.85414532,  76.33504082,
         68.80351382,  53.66706052],
       [ 70.13903576,  75.46674823,  61.26621798,  67.89203982,
         79.91829156,  68.45354036,  97.58612187,  72.71155332,
         50.31499429,  67.71861793],
       [ 64.60460512,  71.82518257,  56.80053842,  65.79272175,
         74.64998395,  77.64191168,  58.83706614,  74.9597005 ,
         73.12667051,  67.26168115],
       [ 72.18392759,  77.54850316,  75.10693855,  71.98817254,
         67.32554527,  67.84111064,  69.21657469,  69.14036002,
         70.85093372,  74.37554729],
       [ 8

## 直接獲取「姓名產生器」的結果。

### 運用爬蟲技術，直接到網站抓取姓名結果，並且變成一個 list 以便進行後續處理。

In [129]:
import requests
from bs4 import BeautifulSoup
from lxml import etree

#User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
# 以上的 User-Agent 資料可以從瀏覽器的開發者工具裡面取得。
headers = {'user-agent': 'User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36'}
res = requests.get('http://www.richyli.com/name/index.asp', headers = headers)
res.encoding = 'big5'
print(res.text)
soup = BeautifulSoup(res.text,'lxml')

# 使用選擇器來選取所需要的區塊。
d =soup.select("td[valign=top]") 
s = d[0].text.strip() # 針對字串清除頭尾的不可見字元。
names = str.split(s, '、') # 字串切割成 list
names = names[:-1] # 捨棄掉最後一個
print(names)


<script type="text/javascript">
window.google_analytics_uacct = "UA-103495-7";
</script>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<HTML lang="zh-TW">
<head>
<title>中文姓名產生器 : 命名、起名、取名參考工具- Chinese Name Generator </title>
<meta name="keywords" content="命名, 起名, 姓名學, 姓名, 藝名, 花名, 名字, 嬰兒命名, 命名軟體, 文學, 創作, 取名, 小說">
<meta name="description" content="提供電腦化產生姓名的快速機制，文字創作者的最愛，本土小說家最常使用的網路工具之一。">
<meta http-equiv="Content-Type" content="text/html; charset=big5">
<link rel="shortcut icon" href="/favicon.ico" />
</head>
<body bgcolor="white">

<table width="700" border="0" align="center">
<tr>
<td colspan="2">
<h1>中文姓名產生器 <a href="history.htm">v3.4</a></h1>

 <form name="form" action="index.asp" method="post" >
    <hr>
    <table width="730" border="0" cellpadding="2" cellspacing="0">
      <tr>
        <td><div align="left"><b>想產生多少名字</b></div></td>
        <td>
          <div align="left">
            <select name="name_count" class="11

In [148]:
import pandas as pd
import os



basepath = 'datas/'
df = pd.DataFrame()

df['name'] = pd.Series(names)
df['exam1'] = pd.Series(np.random.randint(100, size=100))
df['exam2'] = pd.Series(np.random.randint(100, size=100))
df['exam3'] = pd.Series(np.random.randint(100, size=100))

writer = pd.ExcelWriter(basepath+'自己生資料.xlsx')
df.to_excel(writer,'Sheet1')
os.listdir(basepath)


['.DS_Store', '原始資料表.xlsx', '原始資料表_new.xlsx', '自己生資料.xlsx']

# 回歸分析